name = "vue-bookmarks-api"
main = "src/worker.js"
compatibility_date = "2024-01-15"

# KV 存储绑定
[[kv_namespaces]]
binding = "BOOKMARKS_KV"
id = "b0f52d8d37e749a9a5725b04f26412da"
preview_id = "b0f52d8d37e749a9a5725b04f26412da"

# 环境变量
[vars]
ADMIN_PASSWORD = "jisoo521"  # 设置你的管理员密码
RESEND_API_KEY = "re_Zx6mKyWX_MbX5pwweuaE92w4H7Ferxhox"  # Resend API密钥
DEEPSEEK_API_KEY = "sk-d1809f2d4f724f25be37274c77e0e424"  # DeepSeek API密钥

# Cron 触发器 - 每2分钟检查一次是否需要发送邮件
[triggers]
crons = ["*/2 * * * *"]

# 路由配置
[[routes]]
pattern = "www.jisoolove.top/api/*"  # 你的项目访问域名
zone_name = "jisoolove.top"          # 你的根域名
