name = "my-jisoolove"
main = "src/main.js"
compatibility_date = "2024-09-13"

[site]
bucket = "./dist"
entry-point = "."

# 环境变量
[build]
command = "npm install && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# 路由配置 - 确保 SPA routing works
[[routes]]
pattern = "/*"
status = 200
headers = { "Cache-Control" = "public, max-age=0, must-revalidate" }
[[routes]]
pattern = "www.jisoolove.top/api/*"  # 你的项目访问域名
zone_name = "jisoolove.top"          # 你的根域名
