name: Email Sender Service

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run email sender script
        run: node email-sender-github-action.js
        env:
          # Cloudflare配置
          CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
          
          # Resend API密钥
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          
          # DeepSeek API密钥
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          
          # 邮件发送者信息
          FROM_NAME: ${{ secrets.FROM_NAME || 'Jisoo每日一问' }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL || 'noreply@jisoolove.top' }}